// Generated by scripts/generate-sw.mjs. Do not edit.
// Sources: src/sw/service-worker.js + src/sw/routing.js

/**
 * What the service worker should do with a given request.
 *
 * Kept as a pure function in its own file for two reasons. It is the part with
 * real consequences if it is wrong, and a service worker is miserable to test
 * directly. `scripts/generate-sw.mjs` concatenates this into the emitted
 * `sw.js`, and `tests/sw-routing.test.ts` imports it directly, so the thing
 * under test is the thing that ships.
 *
 * Plain JS on purpose: the worker is emitted without a bundler, so this file
 * must be valid in a worker as written.
 *
 * The four outcomes:
 *
 *   'cache-first'   an app asset we precached. Serve from cache, fall back to
 *                   network. These are content-hashed, so a cache hit is never
 *                   stale.
 *   'app-shell'     a navigation to the app itself. Try network, fall back to
 *                   the cached shell so a cold start works with no network.
 *   'passthrough'   go to the network and do not touch the cache.
 *   'ignore'        not ours at all; do not even respond, let the browser do it.
 *
 * The default is deliberately 'passthrough'. Anything this file has not been
 * taught about must not be cached, because the things it has not been taught
 * about are the documentation site and the user's own image data.
 */

/**
 * Paths under the app's own origin that belong to other things.
 *
 * The Pages repo hosts far more than the viewer: a 20 MB VitePress docs site,
 * the embed bundle, example stores, JSON Schemas, marketing and legal pages,
 * and a Google Search Console verification file. A root-scoped worker sees all
 * of it. Serving any of it from a stale cache would be worse than not being
 * offline, and hijacking the Search Console token would quietly break domain
 * verification.
 */
const NOT_THE_APP = [
    'docs/',
    'embed/',
    'examples/',
    'schemas/',
    'screenshots/',
];

/**
 * Root-level pages that are hand-maintained, not emitted by the app build.
 * `deploy.sh` never touches these, so the worker must not either.
 */
const HAND_MAINTAINED_PAGES = [
    'demos.html',
    'privacy.html',
    'publications.html',
    'terms.html',
    'llms.txt',
    'robots.txt',
    'sitemap.xml',
];

/**
 * Decide how to handle one request.
 *
 * Args:
 *     request (object): `{url, mode, method}` — the fields of a real Request
 *         this needs. Passing a plain object keeps it testable.
 *     ctx (object): `{scope, precached}` where `scope` is the worker's scope URL
 *         (always ends in '/') and `precached` is a Set of absolute URLs.
 *
 * Returns:
 *     string: one of 'cache-first', 'app-shell', 'passthrough', 'ignore'.
 */
function classify(request, ctx) {
    const { url, mode = 'no-cors', method = 'GET' } = request;
    const { scope, precached } = ctx;

    // Reason: only GET is cacheable, and a non-GET to our own origin is not
    // something this worker should be interpreting.
    if (method !== 'GET') return 'ignore';

    // Reason: the user's image data, the analytics tables and the Plausible tag
    // are all cross-origin. Caching image data would write customer pixels to
    // disk on whatever machine the browser is on, which contradicts the whole
    // pitch, and Cache Storage ignores Range semantics, which would silently
    // corrupt sharded v3 and Parquet reads. Never touch cross-origin.
    if (!url.startsWith(originOf(scope))) return 'ignore';

    // Reason: requests to our origin but outside our scope are someone else's.
    // With `base: './'` the app can live in a subdirectory, so scope is not
    // necessarily the site root.
    if (!url.startsWith(scope)) return 'ignore';

    const rest = stripQuery(url.slice(scope.length));

    if (NOT_THE_APP.some(p => rest.startsWith(p))) return 'passthrough';
    if (HAND_MAINTAINED_PAGES.includes(rest)) return 'passthrough';

    // Reason: this MUST be tested before the precache lookup. index.html is
    // precached (it has to be, or a cold offline start has nothing to serve)
    // but it is the one precached file whose name is not content-hashed, so
    // answering it cache-first would pin every user to the build they first
    // visited and no deploy would ever reach them. Network-first with a cached
    // fallback is the only correct treatment, and 'app-shell' is what asks for
    // it. `?url=...` deep links land here too, which is why the query string is
    // stripped before comparing.
    if (mode === 'navigate' && (rest === '' || rest === 'index.html')) {
        return 'app-shell';
    }

    // Reason: hashed asset names mean a cache hit can never be stale, so
    // cache-first is safe and is what makes a cold offline start fast.
    if (precached.has(stripQuery(url))) return 'cache-first';

    // Reason: everything else on our origin that we did not precache. Most
    // often a lazily added asset from a newer deploy, or a file belonging to
    // some other part of the site. Fetch it, do not cache it.
    return 'passthrough';
}

/** Origin of a scope URL, including the trailing slash-free host part. */
function originOf(scope) {
    const m = /^[a-z]+:\/\/[^/]+/i.exec(scope);
    return m ? m[0] : scope;
}

/** URL without its query string or fragment. */
function stripQuery(u) {
    return u.split('#')[0].split('?')[0];
}


/**
 * Service worker: makes the viewer work with no network.
 *
 * This file is a template. `scripts/generate-sw.mjs` injects the precache list
 * and a build id, concatenates `src/sw/routing.js`, and writes `build/sw.js`.
 * It is emitted to the build ROOT because a worker's scope defaults to the
 * directory it is served from, GitHub Pages cannot send `Service-Worker-Allowed`
 * to widen it, and the app needs scope over its whole directory.
 *
 * What it caches, and what it refuses to:
 *
 * Only the app's own build output. Not the documentation, not the embed bundle,
 * and above all not image data. Image data is cross-origin, often authenticated,
 * and read with Range requests that Cache Storage does not honour, so caching it
 * would both leak customer pixels onto disk and corrupt sharded reads. See
 * `routing.js`, where that decision is enforced rather than assumed.
 *
 * Eviction is expected, not exceptional. Chrome refused this origin's
 * `navigator.storage.persist()` request even when installed (measured
 * 2026-08-09, see design/001), so the cache lives in the best-effort bucket and
 * can vanish at any time. Every read falls back to the network, and `activate`
 * repairs a partially evicted cache instead of assuming one write lasts
 * forever.
 */

/* eslint-env serviceworker */

// The two placeholders below are filled in by scripts/generate-sw.mjs.
// Do not mention their literal names anywhere else in this file: the generator
// replaces the first occurrence, and a mention in a comment would swallow it.
// The generator asserts exactly one occurrence of each, so this cannot regress
// silently.
const BUILD_ID = '72390dec416b';
const PRECACHE_PATHS = [
    "assets/10501752-B-hwQ8_O.jpg",
    "assets/5025552-C-so2le5.jpg",
    "assets/bia-S-BIAD2339-1b738f80-Cp4QbYea.jpg",
    "assets/bia-S-BIAD2339-22f698e5-S05_SBQq.jpg",
    "assets/bia-S-BIAD2339-84ba3917-l6Tc5v5y.jpg",
    "assets/bia-S-BIAD2339-890dadf6-DdhDGzz0.jpg",
    "assets/bia-S-BIAD2453-2a07fd62-CAPzdH-c.jpg",
    "assets/bia-S-BIAD2973-1a49df5f-LmDYhqR8.jpg",
    "assets/bia-S-BIAD2973-7d2fb3ef-DZJBDSWs.jpg",
    "assets/bia-S-BIAD2973-b8d069cb-o0Ubg1lo.jpg",
    "assets/bia-S-BIAD3221-05940542-C16cHqdr.jpg",
    "assets/bia-S-BIAD3242-81572b29-Bu8ETEa0.jpg",
    "assets/blosc-CINP29Do.js",
    "assets/browser-CSeI90Bu.js",
    "assets/chunk-INHXZS53-CYqy14ta.js",
    "assets/fn-plate-tables-VoGYusJI.js",
    "assets/gzip-BduOtoNN.js",
    "assets/index-CGTCTMpn.js",
    "assets/index-CI0Eyzzp.js",
    "assets/index-DEpKspHo.js",
    "assets/index-DPjWNzhh.css",
    "assets/index-DSGHM4gd.js",
    "assets/index-Dmu9_vye.js",
    "assets/lz4-CvXMSXgq.js",
    "assets/zarr-metadata-normalizer-ecD9Ywx8.js",
    "assets/zlib-BDjr_O7m.js",
    "assets/zstd-Dvw5UDYA.js",
    "favicon-128.png",
    "favicon-16.png",
    "favicon-32.png",
    "favicon-48.png",
    "favicon-64.png",
    "favicon.ico",
    "favicon.svg",
    "index.html",
    "logo192.png",
    "logo512.png"
];

const CACHE = `fn-viewer-${BUILD_ID}`;

/** Absolute URLs of everything we precache, resolved against our own scope. */
function precacheUrls() {
    return PRECACHE_PATHS.map(p => new URL(p, self.registration.scope).href);
}

self.addEventListener('install', (event) => {
    event.waitUntil((async () => {
        const cache = await caches.open(CACHE);
        // Reason: addAll is atomic — one failure discards the lot, which is the
        // behaviour we want. A half-filled cache would produce an app that
        // starts offline and then breaks on a missing chunk, which is harder to
        // diagnose than not starting at all.
        await cache.addAll(precacheUrls());
    })());
    // Reason: deliberately NOT skipWaiting() here. A worker that activates
    // immediately swaps the asset set under a running tab, and deploy.sh
    // deletes the previous build's hashed files, so an open session would start
    // 404ing on its next lazy import. The page asks for the swap when the user
    // accepts the update prompt.
});

self.addEventListener('activate', (event) => {
    event.waitUntil((async () => {
        // Drop caches from older builds.
        const names = await caches.keys();
        await Promise.all(
            names.filter(n => n.startsWith('fn-viewer-') && n !== CACHE)
                 .map(n => caches.delete(n))
        );

        // Reason: repair, not assume. The browser may have evicted part of this
        // cache since install. Re-add only what is missing, and tolerate
        // failure — if we are offline right now there is nothing to fetch, and
        // the fetch handler already falls back to the network.
        try {
            const cache = await caches.open(CACHE);
            const have = new Set((await cache.keys()).map(r => r.url));
            const gone = precacheUrls().filter(u => !have.has(u));
            if (gone.length) await cache.addAll(gone);
        } catch {
            // Offline or still evicting. Nothing useful to do here.
        }

        await self.clients.claim();
    })());
});

self.addEventListener('message', (event) => {
    // Reason: the page owns the decision to swap builds, because only the page
    // knows whether the user is in the middle of something.
    if (event.data === 'fn-skip-waiting') self.skipWaiting();
});

self.addEventListener('fetch', (event) => {
    const decision = classify(
        { url: event.request.url, mode: event.request.mode, method: event.request.method },
        { scope: self.registration.scope, precached: new Set(precacheUrls()) },
    );

    if (decision === 'ignore' || decision === 'passthrough') return;

    if (decision === 'cache-first') {
        event.respondWith((async () => {
            const hit = await caches.match(event.request);
            if (hit) return hit;
            // Reason: a miss here means eviction or a newer deploy. Fetch it and
            // put it back, so the cache heals during normal use.
            const res = await fetch(event.request);
            if (res.ok) {
                const cache = await caches.open(CACHE);
                cache.put(event.request, res.clone());
            }
            return res;
        })());
        return;
    }

    if (decision === 'app-shell') {
        event.respondWith((async () => {
            // Reason: network first for the shell so a deploy is picked up on
            // the next visit rather than being pinned by the cache. The cached
            // copy is the fallback that makes a cold offline start work.
            try {
                return await fetch(event.request);
            } catch {
                const shell = await caches.match(
                    new URL('index.html', self.registration.scope).href
                );
                if (shell) return shell;
                throw new Error('offline and no cached app shell');
            }
        })());
    }
});
